### ISSUE TITLE
Chat Tab Names Unreadable

### ISSUE THREAD

**Issue by jrarmstro** [Quasic/DragonBasher#4]
The names of the chat tabs are unreadable (yellow text on the egg coloured chat background.) 
https://gyazo.com/262fbdd8970b89e87d214b8c7e825185

It seems to be caused by the dragonbasher website's css: 
`<body bgcolor=black link=yellow vlink=yellow alink=yellow>`

The div#CHAT setting of color:navy is overriden by -webkit-link.

**Comment by jrarmstro** [comment]
When viewing the game from the .cgi directly (rather than through the iframe) it functions as expected:
https://gyazo.com/dfb4e063227d5e5cf958f4b111205e3e

**Comment by Quasic** [comment]
Thanks! This is, not amazingly, a known issue, but you described it well. The fix of setting it in the js code would work temporarily, but it should be fixed in css. I was considering restricting the iframe page's link styling, but this code should be made robust enough for other iframes, if possible.

**Comment by Quasic** [comment]
Since this js is injected, we need to inject css along with it. Perhaps a separate css file link tag could be injected instead of the css itself, though jQuery probably has a way to handle this...

**Comment by jrarmstro** [comment]
I've been looking at the inline CSS and thinking it would be nice to use a style sheet instead... it's probably faster on both ends, and it's easier to edit (we can run it through programs to be validated or even use a preprocessor...)

**Comment by Quasic** [comment]
Right, I'm thinking to move the css to a file or files in the 11-gfx repo, where it can be edited along with the images. Some ~~default~~ overriding inline css can be kept, though, to ensure functionality. .. The injected css would probably need its own file, say chat.css, to be injected without interfering with the rest of the document.
